#!/usr/bin/env bash
# ==============================================================================
# AWS Organization Security Group Cleanup & Backup Tool
# Script: cleanup_security_groups.sh
# Purpose: Takes full JSON backups of unattached, non-default Security Groups
#          across accounts and regions, then safely deletes them.
# ==============================================================================

set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

ROLE_NAME="${ROLE_NAME:-OrganizationAccountAccessRole}"
AUDIT_FILE=""
SPECIFIC_ACCOUNTS=""
SPECIFIC_REGIONS=""
SPECIFIC_SG_ID=""
DRY_RUN=true
FORCE=false
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_DIR="${SCRIPT_DIR}/backups/${TIMESTAMP}"

show_help() {
    cat << EOF
AWS Security Group Backup & Safe Cleanup Tool
Backs up and remediates Security Groups across AWS Organization accounts:
- Unattached non-default groups: Safely backed up and DELETED.
- Default VPC groups ('default'): Cannot be deleted by AWS API; safely backed up
  and all INGRESS RULES REMOVED (CIS AWS Foundations Benchmark compliance).

USAGE:
    ./cleanup_security_groups.sh [OPTIONS]

SAFETY CONTROLS:
    By default, this tool runs in DRY-RUN mode. No security groups or rules will be modified
    unless the --execute flag is explicitly supplied.

OPTIONS:
    --execute                   Execute real backup and deletion (default is DRY RUN).
    -y, --yes                   Skip interactive confirmation prompt when executing.
    -f, --audit-file <FILE>     Path to security_audit_report.json generated by audit_security_groups.sh.
                                (Recommended: avoids re-scanning the entire organization).
    -r, --role-name <ROLE>      IAM Role to assume in member accounts.
                                Default: OrganizationAccountAccessRole
    -a, --accounts <ID,ID...>   Filter to specific target Account ID(s).
    -g, --regions <REG,REG...>  Filter to specific AWS Region(s).
    -s, --sg-id <SG_ID>         Target a single specific Security Group ID for backup & deletion.
    -b, --backup-dir <DIR>      Directory to store JSON backups.
                                Default: ./backups/<timestamp>
    -h, --help                  Show this help message and exit.

EXAMPLES:
    # 1. Preview candidates for deletion from previous audit (DRY RUN):
    ./cleanup_security_groups.sh --audit-file ./audit_results/20260926_120000/security_audit_report.json

    # 2. Back up and safely delete unattached security groups with confirmation:
    ./cleanup_security_groups.sh --audit-file ./audit_results/20260926_120000/security_audit_report.json --execute

    # 3. Clean up unattached SGs in a specific account and region directly:
    ./cleanup_security_groups.sh --accounts 111122223333 --regions us-east-1 --execute

    # 4. Target a single unattached security group:
    ./cleanup_security_groups.sh --sg-id sg-0123456789abcdef0 --accounts 111122223333 --regions us-east-1 --execute

EOF
}

# Parse Arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --execute)
            DRY_RUN=false
            shift
            ;;
        -y|--yes)
            FORCE=true
            shift
            ;;
        -f|--audit-file)
            AUDIT_FILE="$2"
            shift 2
            ;;
        -r|--role|--role-name)
            ROLE_NAME="$2"
            shift 2
            ;;
        -a|--accounts)
            SPECIFIC_ACCOUNTS="$2"
            shift 2
            ;;
        -g|--region|--regions)
            SPECIFIC_REGIONS="$2"
            shift 2
            ;;
        -s|--sg-id)
            SPECIFIC_SG_ID="$2"
            shift 2
            ;;
        -b|--backup-dir)
            BACKUP_DIR="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            log_error "Unknown parameter: $1"
            show_help
            exit 1
            ;;
    esac
done

cleanup() {
    clear_assumed_role
}
trap cleanup EXIT INT TERM

log_header "AWS Security Group Backup & Cleanup Tool"

# Verify prerequisites & AWS access
check_prerequisites

# Display Operating Mode
if [[ "${DRY_RUN}" == "true" ]]; then
    log_warn "MODE: DRY-RUN (Simulation only - NO changes will be made to AWS)"
    log_info "To perform real backup and deletion, re-run with: --execute"
else
    log_warn "MODE: EXECUTE (Will back up and PERMANENTLY DELETE unattached security groups)"
fi

# Step 1: Identify Candidates for Remediation
CANDIDATES_JSON="[]"

if [[ -n "${AUDIT_FILE}" ]] && [[ -f "${AUDIT_FILE}" ]]; then
    log_step "Loading candidate security groups from audit report: ${AUDIT_FILE}"
    
    # Filter candidates from audit file:
    # 1. Unattached non-default SGs (TargetAction: DELETE)
    # 2. Default SGs with ingress rules (TargetAction: REVOKE_INGRESS)
    CANDIDATES_JSON=$("${PYTHON_BIN:-python3}" -c "
import sys, json

audit_file = sys.argv[1]
acc_filter = [x.strip() for x in sys.argv[2].split(',') if x.strip()] if len(sys.argv) > 2 and sys.argv[2] else []
reg_filter = [x.strip() for x in sys.argv[3].split(',') if x.strip()] if len(sys.argv) > 3 and sys.argv[3] else []
sg_filter = sys.argv[4].strip() if len(sys.argv) > 4 and sys.argv[4] else ''

with open(audit_file, 'r', encoding='utf-8') as f:
    data = json.load(f)

results = []
for sg in data:
    acc = sg.get('AccountId', '')
    reg = sg.get('Region', '')
    gid = sg.get('GroupId', '')

    if acc_filter and acc not in acc_filter:
        continue
    if reg_filter and reg not in reg_filter:
        continue
    if sg_filter and gid != sg_filter:
        continue

    is_default = sg.get('IsDefault', False) or sg.get('GroupName') == 'default'
    is_attached = sg.get('IsAttached', False)
    rec = sg.get('Recommendation', '')
    ingress_count = sg.get('IngressRulesCount', len(sg.get('IpPermissions', [])))

    if is_default:
        # Default SG: cannot be deleted; candidate for removing ingress rules if any exist
        if ingress_count > 0 or rec == 'DEFAULT_RESTRICT':
            item = dict(sg)
            item['TargetAction'] = 'REVOKE_INGRESS'
            item['IsDefault'] = True
            results.append(item)
    else:
        # Non-default SG: candidate for deletion if unattached
        if not is_attached or rec == 'CAN_DELETE':
            item = dict(sg)
            item['TargetAction'] = 'DELETE'
            item['IsDefault'] = False
            results.append(item)

print(json.dumps(results))
" "${AUDIT_FILE}" "${SPECIFIC_ACCOUNTS:-}" "${SPECIFIC_REGIONS:-}" "${SPECIFIC_SG_ID:-}")

else
    log_step "No audit file provided. Performing live discovery of remediation candidates..."
    # Live scan across accounts
    ACCOUNTS_JSON=$(get_organization_accounts "${SPECIFIC_ACCOUNTS}")
    
    while read -r acc_obj; do
        ACC_ID=$(echo "${acc_obj}" | jq -r '.Id')
        ACC_NAME=$(echo "${acc_obj}" | jq -r '.Name')

        if [[ "${ACC_ID}" == "${CURRENT_ACCOUNT_ID}" ]]; then
            clear_assumed_role
        else
            if ! assume_account_role "${ACC_ID}" "${ROLE_NAME}" "SGCleanup-${ACC_ID}"; then
                log_warn "Skipping account ${ACC_ID}: Unable to assume role '${ROLE_NAME}'."
                continue
            fi
        fi

        REGIONS_JSON=$(get_account_regions "${SPECIFIC_REGIONS}")
        REG_LIST=($(echo "${REGIONS_JSON}" | jq -r '.[]'))

        for REG in "${REG_LIST[@]}"; do
            log_info "Discovering in Account ${ACC_ID} (${ACC_NAME}) | Region ${REG}..."
            
            # Fetch SGs & ENIs
            SGS_RAW=$(aws ec2 describe-security-groups --region "${REG}" --output json 2>/dev/null)
            ENIS_RAW=$(aws ec2 describe-network-interfaces --region "${REG}" --output json 2>/dev/null)

            if [[ -z "${SGS_RAW}" ]]; then continue; fi

            # Extract unattached non-default SGs AND default SGs with ingress rules
            REGION_CANDIDATES=$("${PYTHON_BIN:-python3}" -c "
import sys, json
sgs = json.loads(sys.argv[1]).get('SecurityGroups', [])
enis = json.loads(sys.argv[2]).get('NetworkInterfaces', []) if sys.argv[2] else []
acc_id = sys.argv[3]
acc_name = sys.argv[4]
region = sys.argv[5]
specific_sg = sys.argv[6]

attached_ids = set()
for eni in enis:
    for g in eni.get('Groups', []):
        attached_ids.add(g.get('GroupId'))

results = []
for sg in sgs:
    gid = sg.get('GroupId')
    gname = sg.get('GroupName', '')
    is_default = (gname == 'default')
    ingress_rules = sg.get('IpPermissions', [])
    
    if specific_sg and gid != specific_sg:
        continue
    
    if is_default:
        # Default SG: cannot be deleted; candidate for removing ingress rules if any exist
        if len(ingress_rules) > 0:
            results.append({
                'AccountId': acc_id,
                'AccountName': acc_name,
                'Region': region,
                'GroupId': gid,
                'GroupName': gname,
                'Description': sg.get('Description', ''),
                'VpcId': sg.get('VpcId', ''),
                'IsDefault': True,
                'TargetAction': 'REVOKE_INGRESS',
                'IpPermissions': ingress_rules,
                'IpPermissionsEgress': sg.get('IpPermissionsEgress', []),
                'Tags': sg.get('Tags', [])
            })
    else:
        # Non-default SG: candidate for deletion if unattached
        if gid not in attached_ids:
            results.append({
                'AccountId': acc_id,
                'AccountName': acc_name,
                'Region': region,
                'GroupId': gid,
                'GroupName': gname,
                'Description': sg.get('Description', ''),
                'VpcId': sg.get('VpcId', ''),
                'IsDefault': False,
                'TargetAction': 'DELETE',
                'IpPermissions': ingress_rules,
                'IpPermissionsEgress': sg.get('IpPermissionsEgress', []),
                'Tags': sg.get('Tags', [])
            })

print(json.dumps(results))
" "${SGS_RAW}" "${ENIS_RAW}" "${ACC_ID}" "${ACC_NAME}" "${REG}" "${SPECIFIC_SG_ID:-}")

            if [[ -n "${REGION_CANDIDATES}" ]] && [[ "${REGION_CANDIDATES}" != "[]" ]]; then
                CANDIDATES_JSON=$(jq -s '.[0] + .[1]' <(echo "${CANDIDATES_JSON}") <(echo "${REGION_CANDIDATES}"))
            fi
        done
        clear_assumed_role
    done < <(echo "${ACCOUNTS_JSON}" | jq -c '.[]')
fi

CANDIDATE_COUNT=$(echo "${CANDIDATES_JSON}" | jq '. | length')

if [[ "${CANDIDATE_COUNT}" -eq 0 ]]; then
    log_success "Zero candidates found matching remediation criteria. Nothing to clean up!"
    exit 0
fi

# Step 2: Display Candidate Inventory
DELETE_CANDIDATE_COUNT=$("${PYTHON_BIN:-python3}" -c "import sys, json; print(len([x for x in json.loads(sys.argv[1]) if x.get('TargetAction') == 'DELETE']))" "${CANDIDATES_JSON}")
DEFAULT_CANDIDATE_COUNT=$("${PYTHON_BIN:-python3}" -c "import sys, json; print(len([x for x in json.loads(sys.argv[1]) if x.get('TargetAction') == 'REVOKE_INGRESS']))" "${CANDIDATES_JSON}")

if [[ "${DRY_RUN}" == "true" ]]; then
    log_header "DRY-RUN PREVIEW: What Will Be Deleted / Remediated"
else
    log_header "Remediation Candidates Discovered (${CANDIDATE_COUNT} Groups)"
fi

if [[ -n "${SPECIFIC_ACCOUNTS}" ]]; then
    log_info "Account Filter: Targeting specific account(s) -> ${SPECIFIC_ACCOUNTS}"
else
    log_info "Account Scope: All discovered Organization accounts"
fi

if [[ -n "${SPECIFIC_REGIONS}" ]]; then
    log_info "Region Filter:  Targeting specific region(s)  -> ${SPECIFIC_REGIONS}"
fi

echo ""
"${PYTHON_BIN:-python3}" -c "
import sys, json
candidates = json.loads(sys.argv[1])
is_dry_run = sys.argv[2] == 'true'

for idx, sg in enumerate(candidates, 1):
    act = sg.get('TargetAction', 'DELETE')
    gid = sg.get('GroupId', '')
    gname = sg.get('GroupName', '')
    vpc = sg.get('VpcId', 'N/A')
    acc = sg.get('AccountId', '')
    acc_name = sg.get('AccountName', f'Account-{acc}')
    reg = sg.get('Region', '')
    desc = sg.get('Description', 'No description')
    ingress_rules = sg.get('IpPermissions', [])
    egress_rules = sg.get('IpPermissionsEgress', [])
    
    if act == 'DELETE':
        badge = '[WILL BE DELETED]' if is_dry_run else '[TARGET: DELETE]'
        reason = 'Unattached non-default SG (0 active ENIs). Candidate for backup & permanent deletion.'
    else:
        badge = '[WILL REVOKE INGRESS]' if is_dry_run else '[TARGET: REVOKE INGRESS]'
        reason = f'AWS Default VPC SG. Cannot be deleted via AWS API; will backup and revoke {len(ingress_rules)} inbound rule(s).'

    print(f'[{idx}/{len(candidates)}] {badge}')
    print(f'  • Security Group : {gid} ({gname}) [VPC: {vpc}]')
    print(f'  • Account/Region : {acc_name} ({acc}) | {reg}')
    print(f'  • Rules & State  : {len(ingress_rules)} inbound, {len(egress_rules)} outbound')
    print(f'  • Action Rationale: {reason}')
    print('')
" "${CANDIDATES_JSON}" "${DRY_RUN}"

echo "--------------------------------------------------------------------------------"
printf "${COLOR_WHITE}%-36s : %s${COLOR_RESET}\n" "Total Remediation Candidates" "${CANDIDATE_COUNT}"
printf "${COLOR_GREEN}%-36s : %s${COLOR_RESET}\n" "Security Groups to DELETE" "${DELETE_CANDIDATE_COUNT}"
printf "${COLOR_PURPLE}%-36s : %s${COLOR_RESET}\n" "Default SGs to RESTRICT (Ingress)" "${DEFAULT_CANDIDATE_COUNT}"
printf "${COLOR_WHITE}%-36s : %s${COLOR_RESET}\n" "Target Accounts Scope" "${SPECIFIC_ACCOUNTS:-All Accounts}"
printf "${COLOR_WHITE}%-36s : %s${COLOR_RESET}\n" "Target Regions Scope" "${SPECIFIC_REGIONS:-All Enabled Regions}"
printf "${COLOR_WHITE}%-36s : %s${COLOR_RESET}\n" "Planned Backup Destination" "${BACKUP_DIR}"
echo "--------------------------------------------------------------------------------"

if [[ "${DRY_RUN}" == "true" ]]; then
    echo ""
    log_success "DRY-RUN COMPLETED: No AWS resources were modified or deleted."
    log_info "To execute the actual backup, deletion, and rule removal, re-run with:"
    EXEC_CMD="$0 --execute"
    if [[ -n "${AUDIT_FILE}" ]]; then EXEC_CMD="${EXEC_CMD} --audit-file \"${AUDIT_FILE}\""; fi
    if [[ -n "${SPECIFIC_ACCOUNTS}" ]]; then EXEC_CMD="${EXEC_CMD} --accounts \"${SPECIFIC_ACCOUNTS}\""; fi
    if [[ -n "${SPECIFIC_REGIONS}" ]]; then EXEC_CMD="${EXEC_CMD} --regions \"${SPECIFIC_REGIONS}\""; fi
    if [[ -n "${SPECIFIC_SG_ID}" ]]; then EXEC_CMD="${EXEC_CMD} --sg-id \"${SPECIFIC_SG_ID}\""; fi
    printf "    ${COLOR_CYAN}%s${COLOR_RESET}\n\n" "${EXEC_CMD}"
    exit 0
fi

# Step 3: Confirmation Prompt for EXECUTE Mode
if [[ "${FORCE}" != "true" ]]; then
    echo ""
    printf "${COLOR_RED}WARNING: You are about to remediate ${CANDIDATE_COUNT} security group(s):${COLOR_RESET}\n"
    if [[ "${DELETE_CANDIDATE_COUNT}" -gt 0 ]]; then
        printf " - ${DELETE_CANDIDATE_COUNT} unattached security group(s) will be PERMANENTLY DELETED.\n"
    fi
    if [[ "${DEFAULT_CANDIDATE_COUNT}" -gt 0 ]]; then
        printf " - ${DEFAULT_CANDIDATE_COUNT} default security group(s) will have their INGRESS RULES REVOKED.\n"
    fi
    printf "All original definitions and rules will be safely backed up to '${BACKUP_DIR}' before modification.\n\n"
    read -r -p "Type 'CONFIRM' to proceed: " confirmation
    if [[ "${confirmation}" != "CONFIRM" && "${confirmation}" != "DELETE" ]]; then
        log_warn "Confirmation aborted by user. Exiting without changes."
        exit 0
    fi
fi

# Step 4: Execute Backup and Remediation
mkdir -p "${BACKUP_DIR}"
MANIFEST_FILE="${BACKUP_DIR}/backup_manifest.json"
echo "[]" > "${MANIFEST_FILE}"

SUCCESS_COUNT=0
DEFAULT_RESTRICTED_COUNT=0
DEPENDENCY_SKIPPED_COUNT=0
ERROR_COUNT=0

log_header "Executing Backups and Remediation"

while read -r candidate; do
    ACC_ID=$(echo "${candidate}" | jq -r '.AccountId')
    ACC_NAME=$(echo "${candidate}" | jq -r '.AccountName')
    if [[ -z "${ACC_NAME}" || "${ACC_NAME}" == "null" ]]; then ACC_NAME="Account-${ACC_ID}"; fi
    REG=$(echo "${candidate}" | jq -r '.Region')
    SG_ID=$(echo "${candidate}" | jq -r '.GroupId')
    SG_NAME=$(echo "${candidate}" | jq -r '.GroupName')
    VPC_ID=$(echo "${candidate}" | jq -r '.VpcId')
    DESC=$(echo "${candidate}" | jq -r '.Description')
    IS_DEFAULT=$(echo "${candidate}" | jq -r '.IsDefault')
    TARGET_ACTION=$(echo "${candidate}" | jq -r '.TargetAction')
    if [[ -z "${TARGET_ACTION}" || "${TARGET_ACTION}" == "null" ]]; then
        if [[ "${IS_DEFAULT}" == "true" || "${SG_NAME}" == "default" ]]; then
            TARGET_ACTION="REVOKE_INGRESS"
        else
            TARGET_ACTION="DELETE"
        fi
    fi

    log_step "Processing [${ACC_ID}] ${REG} | ${SG_ID} (${SG_NAME}) - Action: ${TARGET_ACTION}..."

    # Authenticate to target account
    if [[ "${ACC_ID}" == "${CURRENT_ACCOUNT_ID}" ]]; then
        clear_assumed_role
    else
        if ! assume_account_role "${ACC_ID}" "${ROLE_NAME}" "SGCleanup-${ACC_ID}"; then
            log_error "Failed to assume role in ${ACC_ID}. Skipping ${SG_ID}."
            ((ERROR_COUNT++))
            continue
        fi
    fi

    # Safety Guard 1: Fetch fresh security group details from AWS to ensure exact rule capture
    SG_DETAILS_RAW=$(aws ec2 describe-security-groups --group-ids "${SG_ID}" --region "${REG}" --output json 2>/dev/null)
    if [[ $? -ne 0 ]] || [[ -z "${SG_DETAILS_RAW}" ]]; then
        log_warn "Security group ${SG_ID} no longer exists in ${REG}. Skipping."
        clear_assumed_role
        continue
    fi

    SG_OBJ=$(echo "${SG_DETAILS_RAW}" | jq '.SecurityGroups[0]')

    # Action-Specific Pre-Checks:
    if [[ "${TARGET_ACTION}" == "DELETE" ]]; then
        # Safety Guard 2: Live check that ENI count is still 0 (prevents race condition)
        LIVE_ENI_COUNT=$(aws ec2 describe-network-interfaces --filters "Name=group-id,Values=${SG_ID}" --region "${REG}" --query 'length(NetworkInterfaces)' --output text 2>/dev/null || echo 0)
        if [[ "${LIVE_ENI_COUNT}" -gt 0 ]]; then
            log_warn "SAFETY TRIP: Security group ${SG_ID} now has ${LIVE_ENI_COUNT} active ENI(s) attached! Skipping deletion."
            clear_assumed_role
            continue
        fi

        # Safety Guard 3: Double check not default SG
        if [[ "${SG_NAME}" == "default" ]]; then
            log_warn "Safety Check: ${SG_ID} is a default security group. Cannot be deleted."
            clear_assumed_role
            continue
        fi
    fi

    # --- Phase A: Create Backup ---
    # Sanitize account and SG names for folder/file path
    SAFE_ACC_NAME=$(echo "${ACC_NAME}" | tr -cs 'a-zA-Z0-9_-' '_')
    SAFE_SG_NAME=$(echo "${SG_NAME}" | tr -cs 'a-zA-Z0-9_-' '_')
    ACC_BACKUP_DIR="${BACKUP_DIR}/${ACC_ID}_${SAFE_ACC_NAME}/${REG}"
    mkdir -p "${ACC_BACKUP_DIR}"

    BACKUP_FILE="${ACC_BACKUP_DIR}/${SG_ID}_${SAFE_SG_NAME}.json"

    # Construct complete backup document and update manifest
    "${PYTHON_BIN:-python3}" -c "
import sys, json, datetime
sg_obj = json.loads(sys.argv[1])
acc_id = sys.argv[2]
acc_name = sys.argv[3]
region = sys.argv[4]
backup_file = sys.argv[5]
manifest_file = sys.argv[6]
target_action = sys.argv[7]

metadata = {
    'BackupTimestamp': datetime.datetime.now(datetime.timezone.utc).isoformat(),
    'AccountId': acc_id,
    'AccountName': acc_name,
    'Region': region,
    'GroupId': sg_obj.get('GroupId'),
    'GroupName': sg_obj.get('GroupName'),
    'Description': sg_obj.get('Description'),
    'VpcId': sg_obj.get('VpcId'),
    'ActionTaken': target_action,
    'BackupFile': backup_file,
    'Tool': 'AWS Security Group Audit & Cleanup Utility'
}

backup = {
    'BackupMetadata': metadata,
    'SecurityGroup': sg_obj
}

with open(backup_file, 'w', encoding='utf-8') as f:
    json.dump(backup, f, indent=2)

manifest_data = []
try:
    with open(manifest_file, 'r', encoding='utf-8') as mf:
        manifest_data = json.load(mf)
        if not isinstance(manifest_data, list):
            manifest_data = []
except Exception:
    manifest_data = []

manifest_data.append(metadata)
with open(manifest_file, 'w', encoding='utf-8') as mf:
    json.dump(manifest_data, mf, indent=2)
" "${SG_OBJ}" "${ACC_ID}" "${ACC_NAME}" "${REG}" "${BACKUP_FILE}" "${MANIFEST_FILE}" "${TARGET_ACTION}"

    if [[ ! -f "${BACKUP_FILE}" ]]; then
        log_error "Failed to write backup file: ${BACKUP_FILE}. Aborting remediation of ${SG_ID}."
        ((ERROR_COUNT++))
        clear_assumed_role
        continue
    fi

    log_success "Backup preserved -> ${BACKUP_FILE}"

    # --- Phase B: Execute Remediation Action ---
    if [[ "${TARGET_ACTION}" == "REVOKE_INGRESS" ]]; then
        # Default SG: Remove all ingress rules only (cannot be deleted)
        INGRESS_RULES=$(echo "${SG_OBJ}" | jq -c '.IpPermissions // []')
        INGRESS_COUNT=$(echo "${SG_OBJ}" | jq '.IpPermissions | length')

        if [[ "${INGRESS_COUNT}" -gt 0 ]]; then
            log_step "Default SG ${SG_ID}: Revoking ${INGRESS_COUNT} inbound rule(s)..."
            REVOKE_OUTPUT=$(aws ec2 revoke-security-group-ingress \
                --group-id "${SG_ID}" \
                --ip-permissions "${INGRESS_RULES}" \
                --region "${REG}" 2>&1)
            REVOKE_STATUS=$?

            if [[ ${REVOKE_STATUS} -eq 0 ]]; then
                log_success "Default SG ${SG_ID}: Successfully revoked all ${INGRESS_COUNT} inbound rule(s)."
                ((DEFAULT_RESTRICTED_COUNT++))
            else
                log_error "Default SG ${SG_ID}: Failed to revoke inbound rules: ${REVOKE_OUTPUT}"
                ((ERROR_COUNT++))
            fi
        else
            log_info "Default SG ${SG_ID}: Ingress rules already clean (0 rules)."
            ((DEFAULT_RESTRICTED_COUNT++))
        fi

    elif [[ "${TARGET_ACTION}" == "DELETE" ]]; then
        # Non-default SG: Delete security group
        DELETE_OUTPUT=$(aws ec2 delete-security-group --group-id "${SG_ID}" --region "${REG}" 2>&1)
        DELETE_STATUS=$?

        if [[ ${DELETE_STATUS} -eq 0 ]]; then
            log_success "Deleted unattached security group ${SG_ID} (${SG_NAME})"
            ((SUCCESS_COUNT++))
        else
            if echo "${DELETE_OUTPUT}" | grep -q "DependencyViolation"; then
                log_warn "DependencyViolation: ${SG_ID} is referenced by another security group rule. Preserved backup, skipped deletion."
                ((DEPENDENCY_SKIPPED_COUNT++))
            else
                log_error "Failed to delete ${SG_ID}: ${DELETE_OUTPUT}"
                ((ERROR_COUNT++))
            fi
        fi
    fi

    clear_assumed_role

done < <(echo "${CANDIDATES_JSON}" | jq -c '.[]')

# Step 5: Final Execution Summary
log_header "Remediation & Backup Summary"

printf "${COLOR_WHITE}%-34s : %s${COLOR_RESET}\n" "Total Candidates Targeted" "${CANDIDATE_COUNT}"
printf "${COLOR_GREEN}%-34s : %s${COLOR_RESET}\n" "Unattached SGs Deleted" "${SUCCESS_COUNT}"
printf "${COLOR_PURPLE}%-34s : %s${COLOR_RESET}\n" "Default SGs Restricted (Ingress)" "${DEFAULT_RESTRICTED_COUNT}"
printf "${COLOR_YELLOW}%-34s : %s${COLOR_RESET}\n" "Skipped (Cross-SG Dependencies)" "${DEPENDENCY_SKIPPED_COUNT}"
printf "${COLOR_RED}%-34s : %s${COLOR_RESET}\n" "Errors / Skipped" "${ERROR_COUNT}"
echo ""
log_success "Master Backup Manifest: ${MANIFEST_FILE}"
log_info "All security group rules, tags, and settings are fully archived."
log_info "To restore any group or revoked rules if needed, use: ./restore_security_groups.sh --backup-file <path_to_json>"

exit 0
